language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-beta
cache: yarn
before_script:
- mkdir -p ~/bin
- ln -s /usr/bin/google-chrome-beta ~/bin/google-chrome
- export PATH=$HOME/bin:$PATH
- npm run build
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
