# GitHub action that automatically adds newly filed issues to the Lit project.
# See https://github.com/leonsteinhaeuser/project-beta-automations for documentation.
on:
  issues:
    types: [opened]
jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Lit project
        uses: leonsteinhaeuser/project-beta-automations@v1.1.0
        with:
          gh_token: ${{ secrets.LIT_ROBOT_AUTOMATION_PAT }}
          organization: lit
          project_id: 4
          resource_node_id: ${{ github.event.issue.node_id }}
