name: Tests

on: [push, pull_request]

jobs:
  benchmarks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Restore node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          # Bump the number after `lit-1.x-node-modules` to force a cache
          # update. Note there are cache actions in other jobs in this file that
          # should all keep keys in sync.
          key: lit-1.x-node-modules-0-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: NPM install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run benchmarks
        env:
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
          REPO_SLUG: ${{ github.repository }}
          COMMIT: ${{ github.sha }}
          HEAD_REF: ${{ github.head_ref }}
          EVENT_NAME: ${{ github.event_name }}
        run: ./benchmarks.sh
