name: Benchmarks

on: [pull_request]

jobs:
  benchmarks:
    name: benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Benchmark lit-html/kitchen-sink-render
        run: |
          cd packages/benchmarks
          npx tachometer \
            --config lit-html/kitchen-sink/tachometer-render.json \
            --json-file lit-html/kitchen-sink/results-render.json

      - name: Report lit-html-kitchen-sink-render
        uses: andrewiggins/tachometer-reporter-action@v1
        with:
          report-id: lit-html-kitchen-sink-render
          path: packages/benchmarks/lit-html/kitchen-sink/results-render.json
          pr-bench-name: this-change
          base-bench-name: tip-of-tree

      - name: Benchmark lit-html/kitchen-sink-update
        run: |
          cd packages/benchmarks
          npx tachometer \
            --config lit-html/kitchen-sink/tachometer-update.json \
            --json-file lit-html/kitchen-sink/results-update.json

      - name: Report lit-html-kitchen-sink-update
        uses: andrewiggins/tachometer-reporter-action@v1
        with:
          report-id: lit-html-kitchen-sink-update
          path: packages/benchmarks/lit-html/kitchen-sink/results-update.json
          pr-bench-name: this-change
          base-bench-name: tip-of-tree

      - name: Benchmark lit-html/kitchen-sink-update-nop
        run: |
          cd packages/benchmarks
          npx tachometer \
            --config lit-html/kitchen-sink/tachometer-update-nop.json \
            --json-file lit-html/kitchen-sink/results-update-nop.json

      - name: Report lit-html-kitchen-sink-update-nop
        uses: andrewiggins/tachometer-reporter-action@v1
        with:
          report-id: lit-html-kitchen-sink-render
          path: packages/benchmarks/lit-html/kitchen-sink/results-update-nop.json
          pr-bench-name: this-change
          base-bench-name: tip-of-tree

      - name: Benchmark lit-element/stub1
        run: |
          cd packages/benchmarks
          npx tachometer \
            --config lit-element/stub1/tachometer.json \
            --json-file lit-element/stub1/results.json

      - name: Report lit-element-stub1
        uses: andrewiggins/tachometer-reporter-action@v1
        with:
          report-id: lit-element-stub1
          path: packages/benchmarks/lit-element/stub1/results.json
          pr-bench-name: this-change
          base-bench-name: tip-of-tree
