name: Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    # When lit-robot creates a release PR, skip this check as it will always
    # fail.
    if: ${{ github.actor != 'lit-robot' }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache-dependency-path: package-lock.json

      - name: NPM install
        run: |
          git checkout main
          git checkout ${{ github.sha }}
          npm ci

      - name: Lint
        run: npm run lint

      - name: Changeset
        # Enforce that all PRs that change packages need changesets. Changes
        # without changesets result in this job failing.
        run: npm run changeset status -- --since=main

  tests-local:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install playwright deps
        run: npx playwright install-deps

      - name: NPM install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        env:
          BROWSERS: preset:local
          CONCURRENT_BROWSERS: 3
        run: npm run test

  windows-tools:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          # Pin to avoid version with problematic npm. See https://github.com/npm/cli/issues/4980
          # TODO(augustinekim) Unpin when latest node installed by action includes fixed npm
          node-version: 16.15.0
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: NPM install
        run: npm ci

      - name: Test
        env:
          RUN_BROWSER_TESTS: false
        run: npm run test:windows
