name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: microsoft/playwright-github-action@v1

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        # Don't install concurrently because if multiple playwright postinstall
        # scripts are running at the same time, they will frequently collide and
        # crash. See https://github.com/microsoft/playwright/issues/3912.
        run: npm run bootstrap -- --concurrency=1

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
